export const ADD_FAVORITE = "ADD_FAVORITE";
export const REMOVE_FAVORITE = "REMOVE_FAVORITE";
export const REMOVE_ALL_FAVORITE = "REMOVE_ALL_FAVORITE";
export const UPDATE_FROM_FIRESTORE = "UPDATE_FROM_FIRESTORE";